#!/usr/bin/env perl

# Usage: perl utils/developer/bump-requires dist.ini

# Bumps the dist.ini versions to whatever's working on the computer it's run on

# perl -pi
BEGIN { $^I = ""; }

use 5.010;
use Moose;
use Class::Load 'load_class';
use Module::CoreList;

my $module_get = qr/
    ^
    (?<mod>[\w:]+)
    (?<white>\s*)
    = \s*
    (?<vers>.+)
    $
/x;

my $seen_prereq;
while (<>) {
    chomp $_;

    $seen_prereq = 1 if /^\[Prereq/;

    if ($seen_prereq and $_ ~~ $module_get) {
        my $in_core = Module::CoreList->first_release($+{mod});
        if (not $in_core
            and $+{vers} ne '0'
            and $+{mod} ne 'Term::ReadLine::Gnu'
            and $+{mod} ne 'perl') {
            load_class($+{mod});

            no strict 'refs';
            if (my $ver = ${ $+{mod} . '::VERSION' }) {
                say $+{mod}, $+{white}, "= $ver";
                next;
            }
        }
    }

    say;
}
