#!/usr/bin/env perl

# ln -s utils/developer/git-pre-commit .git/hooks/pre-commit

use strict;
use warnings;

my $old = qx"git rev-parse HEAD:lib/Hailo.pm 2>/dev/null";
my $new = qx"git rev-parse :lib/Hailo.pm 2>/dev/null";

if (($? >> 8) != 0 || $old ne $new) {
    $ENV{PERL_UNICODE} = 'O';
    system qq[ack -h '^=encoding' -A 9001 lib/Hailo.pm > README.pod];
    system "git add README.pod";
}
