#!/usr/bin/perl
use Moose;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use Hal;
use Encode qw(decode);

# use utf8 everywhere
$_ = decode('utf8', $_) for @ARGV;
binmode $_, ':encoding(utf8)' for (*STDIN, *STDOUT, *STDERR);

Hal->new_with_options->run;

=encoding utf8

=head1 NAME

hal - Command-line interface to the L<Hal|Hal> Markov bot

=head1 SYNOPSIS

B<hal> <options>

 Options:
   -l STRING, --learn=NAME      Learn from STRING
   -t FILE,   --train=FILE      Learn from all the lines in FILE
   -r STRING, --reply=STRING    Reply to STRING
   -o INT,    --order=INT       Change Markov order from 5 to INT
   -b FILE,   --brain=FILE      Load/save brain to/from FILE
   -S CLASS,  --storage=CLASS   Use storage CLASS instead of 'Perl'
   -T CLASS,  --tokenizer=CLASS Use tokenizer CLASS instead of 'Generic'
   -h,        --help            This help message
   -v,        --version         Print verion and exit

Note: All input/output and files are assumed to be UTF-8 encoded.

=head1 DESCRIPTION

See the documentation for L<Hal|Hal> for more information.

=head1 AUTHOR

Hinrik E<Ouml>rn SigurE<eth>sson, hinrik.sig@gmail.com

=head1 LICENSE AND COPYRIGHT

Copyright 2010 Hinrik E<Ouml>rn SigurE<eth>sson

This program is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
