use strict;
use warnings;
use File::Spec::Functions 'catfile';
use Test::More tests => 7;
use Test::Script;
use_ok 'Hailo';
use_ok 'Hailo::Storage';
use_ok 'Hailo::Storage::Perl';
use_ok 'Hailo::Storage::SQLite';
use_ok 'Hailo::Tokenizer';
use_ok 'Hailo::Tokenizer::Generic';
script_compiles_ok(catfile('script', 'hailo'));
