use strict;
use warnings;
use File::Spec::Functions 'catfile';
use Test::More tests => 7;
use Test::Script;
use_ok 'Hal';
use_ok 'Hal::Storage';
use_ok 'Hal::Storage::Perl';
use_ok 'Hal::Storage::SQLite';
use_ok 'Hal::Tokenizer';
use_ok 'Hal::Tokenizer::Generic';
script_compiles_ok(catfile('script', 'hal'));
